name: iOS Build and Deploy
run-name: Build and Deploy to TestFlight by @${{ github.actor }}

on:
  workflow_dispatch:  # Manual trigger

jobs:
  upload:
    name: Build and upload to TestFlight
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Set up environment
        env:
          DECRYPTION_PASS_CERTIFICATE: '${{ secrets.DECRYPTION_PASS_CERTIFICATE }}'
          DECRYPTION_PASS_PROFILE: '${{ secrets.DECRYPTION_PASS_PROFILE }}'
          KEYCHAIN_EXPORT: '${{ secrets.KEYCHAIN_EXPORT }}'
        run: |
          # Make the script executable
          chmod +x ./.github/scripts/set_certificates.sh
          # add a distribution certificate to the keychain
          ./.github/scripts/set_certificates.sh

      - name: Run fastlane
        env:
          APP_SPECIFIC_PASS: '${{ secrets.APP_SPECIFIC_PASS }}'
        run: |
          # build and upload to Apple Store Connect (caffeinate is used to prevent the mac from falling asleep)
          caffeinate fastlane prod # Run fastline script